### ISSUE TITLE
API info is included in plaintext in your repo

### ISSUE THREAD

**Issue by estsauver** [AdrianArtiles/foxslide#1]
Hi There,

Your API client ID and secret for instagram are committed in plaintext in the custom.js file. I don't know if you're okay with that becoming public but I thought you should know.

**Comment by AdrianArtiles** [comment]
Thank you for letting me know, this is definitely an oversight. Those credentials were committed before I decided to open source this theme, and after deciding to open source it I neglected to go through with a more thorough security audit.

The instagram credentials have been reset and it will be removed from version control shortly. In the near future I plan to remove all things specific to me and have it instead pull from `_config.yml`.

Thanks again for your help!

**Comment by estsauver** [comment]
Hey, I'm sorry, I didn't actually happen to see a way to get a response
token directly from their api. Is there a reasonable way to get a response
token from their oauth implementation easily?

**Comment by AdrianArtiles** [comment]
The steps to get the access token for client side app like this javascript plugin are outlined [here, in the instagram developer documentation for authentication](http://instagram.com/developer/authentication/), just scroll to the section titled `Client-Side (Implicit) Authentication`.

Hope this helps!

**Comment by estsauver** [comment]
Ahh, gotchya. Thanks a ton. I appreciate it man. That's a rather nice
theme. I'll be playing with it over the next few weeks. Would you be
receptive to a pull request to normalize the height of the blogpost
summaries on the main page?

~Earl

**Comment by AdrianArtiles** [comment]
Thanks, and glad I could help!

As for normalizing; I thought about it briefly but went with the height of the summaries being a function of the length of the excerpt (determined by the use of the `<!--more-->` tag) to avoid too much or not enough whitespace, with excerpts being as long or as short as the author feels they need to be. 

However I gave all of 20 seconds of thought to it and could see how it could be attractive to have them all the same height, with the trade off of it being too much whitespace in some cases, or forcing a shorter excerpt in other cases.

Could really see it going either way, but I'd want to see how'd it look and see if the standardization makes it look good enough the settle with forcing an excerpt of a maximum length. I'll find some time to whip it up and look myself, but feel free to create an example and we can decide then.

But in general I'm very open to pull requests, I know there's a lot that can be improved on.

Thanks again!
