### ISSUE TITLE
This plugin not getting installed

### ISSUE THREAD

**Issue by harit-sunrun** [AdrianArtiles/foxslide#2]
$ rake generate
/Users/hhimanshu/.rvm/gems/ruby-1.9.2-p318/gems/bundler-1.2.1/lib/bundler/runtime.rb:197: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
## Generating Site with Jekyll

/Users/hhimanshu/.rvm/gems/ruby-1.9.2-p318/gems/bundler-1.2.1/lib/bundler/runtime.rb:197: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
overwrite source/stylesheets/screen.css 
/Users/hhimanshu/.rvm/gems/ruby-1.9.2-p318/gems/bundler-1.2.1/lib/bundler/runtime.rb:197: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
/Users/hhimanshu/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/psych.rb:148:in `parse': couldn't parse YAML at line 62 column 0 (Psych::SyntaxError)
    from /Users/hhimanshu/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/psych.rb:148:in`parse_stream'
    from /Users/hhimanshu/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/psych.rb:119:in `parse'
    from /Users/hhimanshu/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/psych.rb:106:in`load'
    from /Users/hhimanshu/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/psych.rb:205:in `load_file'
    from /Users/hhimanshu/.rvm/gems/ruby-1.9.2-p318/gems/jekyll-0.11.2/lib/jekyll.rb:119:in`configuration'
    from /Users/hhimanshu/.rvm/gems/ruby-1.9.2-p318/gems/jekyll-0.11.2/bin/jekyll:207:in `<top (required)>'
    from /Users/hhimanshu/.rvm/gems/ruby-1.9.2-p318/bin/jekyll:19:in`load'
    from /Users/hhimanshu/.rvm/gems/ruby-1.9.2-p318/bin/jekyll:19:in `<main>'
hhimanshu@air~/code/p/python/blog/octopress - 22:22:25 (source) $ rake generate

What is the missing thing?

**Comment by AdrianArtiles** [comment]
Looks like possible error in some `YAML` file. do you have this error with other themes?

**Comment by AdrianArtiles** [comment]
closing as further information has not been provided, and it currently appears to not be related to this theme
